version: '2'
services:

    redis:
        image: redis:alpine
        command: redis-server --requirepass pass
        container_name: redis
        ports:
          - 6379:6379

    php7:
        build: ./dckr/php7
        container_name: php7.1
        links:
          - postgre
          - redis
          - rabbitmq

        volumes:
          - ./conf/freetds.conf:/etc/freetds/freetds.conf

        volumes_from:
          - data 

    nginx:
        image: nginx:1.11
        container_name: nginx
        ports:
          - 8000:8000
          - 8001:8001

        links:
          - php7

        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

        volumes_from:
          - data

    postgre:
        restart: always
        image: postgres:9.6-alpine
        container_name: postgresql
        ports:
          - "5432:5432"
        environment:
          - DEBUG=false

          - POSTGRES_USER=db
          - POSTGRES_PASSWORD=db
          - POSTGRES_DB=db

        volumes:
          - ./data/postgres:/var/lib/postgresql/data

        volumes_from:
          - dataBackup

    postgreTesting:
        restart: always
        image: postgres:9.6-alpine
        container_name: postgresql_testing
        ports:
          - "5433:5432"
        environment:
          - DEBUG=false

          - POSTGRES_USER=db_testing
          - POSTGRES_PASSWORD=db_testing
          - POSTGRES_DB=db_testing

        volumes:
          - ./data/postgresTesting:/var/lib/postgresql/data

        volumes_from:
          - dataBackup

    rabbitmq:
        build: ./dckr/rabbitmq
        container_name: rabbitMQ
        ports:
          - 5672:5672
          - 15672:15672
          - 15674:15674
        environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=pass

    data:
        image: busybox:latest

        volumes:
          - ./app:/srv

    dataBackup:
        image: busybox:latest

        volumes:
          - ./data/backup:/mnt/backup
